# Developers:
#
#  This file is under version control; changes made here will affect everyone.
#  If you need to customise just for yourself, add your personal overrides to docker-compose.developer.yml

# Networking:
#
#  This setup runs containers on the same network as the database container, with the
#     network_mode: service:db
#  definition. This allows "forwardPorts" in devcontainer.json to include 5432 (postgres),
#  6437 (redis), 8123 (tasks emulator). Use "forwardPorts instead of "ports" properties here,
#  to enable forwarding from a Codespace (which doesn't work otherwise).

services:
  web:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        INSTALL_NODE: 'true'
        NODE_VERSION: 'lts/*'

    environment:
      - DATABASE_URL=postgres://postgres_user:postgres_password@localhost/postgres_db
      - DJANGO_SETTINGS_MODULE=tests.server.settings
      - DATABASE_ENGINE=postgres

    # Map the current directory containing code
    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends
    command: sleep infinity

    # Run on the same network as the database container
    network_mode: service:db

    # Use the non-root user for all processes
    user: vscode

    # Enable use of a ptrace-based debugger like C++, Go, and Rust or a profiler like Austin
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Ensure the database is started so that test commands and django server can start
    depends_on:
      - db

  tasks:
    image: ghcr.io/aertje/cloud-tasks-emulator:latest
    command: -host 0.0.0.0 -port 8123 -queue "projects/octue-django-gcp/locations/europe-west1/queues/example-primary"
    network_mode: service:db
    depends_on:
      - db

  db:
    image: postgres:13.0
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
